"""
explainability/report_generator.py
=====================================
Auto-generates incident reports from ACD session data.

For each significant incident (host compromise, drift event, attacker
type change), the ``ReportGenerator`` calls the LLM to produce a
structured incident report in Markdown format, which can then be
converted to PDF or served directly from the API.

Report types
------------
    INCIDENT  : Host compromise or active attack
    DRIFT     : Concept drift detection + EWC adaptation event
    SUMMARY   : End-of-session summary across all incidents

Usage
-----
    generator = ReportGenerator(llm=llm_client)

    report = generator.generate({
        "incident_id":    "INC-2024-0042",
        "title":          "Log4Shell Exploitation — Host-3",
        "severity":       "CRITICAL",
        "cve_ids":        ["CVE-2021-44228"],
        "technique_ids":  ["T1190", "T1059"],
        "hosts_affected": ["Host-3", "Host-1"],
        "actions_taken":  ["Remove Host-3", "Isolate Host-3", "Deploy Decoy"],
        "timeline": [
            {"timestamp": "14:32:01", "event": "Initial compromise detected"},
            {"timestamp": "14:32:05", "event": "Malware removed"},
            {"timestamp": "14:32:06", "event": "Host-3 isolated"},
        ],
        "drift_detected":    False,
        "forgetting_delta":  None,
    })

    # Access the report
    print(report.markdown)
    report.save("data/incidents/INC-2024-0042.md")
"""

from __future__ import annotations

import logging
import re
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

from explainability.llm.client import LLMClient
from explainability.llm.prompts import PromptLibrary
from explainability.llm.token_counter import TokenCounter

logger = logging.getLogger(__name__)

# Report output formats
FMT_MARKDOWN = "markdown"
FMT_PDF      = "pdf"
FMT_HTML     = "html"

# Incident severity colours for HTML/PDF rendering
_SEVERITY_COLOURS = {
    "CRITICAL": "#ff3355",
    "HIGH":     "#ffaa00",
    "MEDIUM":   "#00aaff",
    "LOW":      "#00ff88",
}


@dataclass
class IncidentReport:
    """
    Structured incident report generated by the LLM pipeline.

    Attributes
    ----------
    incident_id : str
    title : str
    severity : str
    report_type : str
        ``"INCIDENT"``, ``"DRIFT"``, or ``"SUMMARY"``.
    markdown : str
        Full report content in Markdown format.
    sections : dict
        Parsed sections: executive_summary, technical_details, impact,
        defender_response, timeline, recommendations.
    cve_ids : list[str]
    technique_ids : list[str]
    hosts_affected : list[str]
    actions_taken : list[str]
    generated_at : str
        ISO 8601 timestamp.
    latency_s : float
    tokens_used : int
    """
    incident_id:    str
    title:          str
    severity:       str                   = "MEDIUM"
    report_type:    str                   = "INCIDENT"
    markdown:       str                   = ""
    sections:       Dict[str, str]        = field(default_factory=dict)
    cve_ids:        List[str]             = field(default_factory=list)
    technique_ids:  List[str]             = field(default_factory=list)
    hosts_affected: List[str]             = field(default_factory=list)
    actions_taken:  List[str]             = field(default_factory=list)
    generated_at:   str                   = ""
    latency_s:      float                 = 0.0
    tokens_used:    int                   = 0

    def save(self, path: str) -> Path:
        """
        Save the report to a Markdown file.

        Parameters
        ----------
        path : str
            Destination file path (should end in ``.md``).

        Returns
        -------
        Path
        """
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(self.markdown, encoding="utf-8")
        logger.info("Incident report saved to: %s", p)
        return p

    def save_html(self, path: str) -> Path:
        """Convert to HTML and save."""
        html = self._markdown_to_html()
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(html, encoding="utf-8")
        logger.info("Incident report HTML saved to: %s", p)
        return p

    def to_dict(self) -> Dict[str, Any]:
        """Return JSON-serialisable dict for the API response."""
        return {
            "incident_id":    self.incident_id,
            "title":          self.title,
            "severity":       self.severity,
            "report_type":    self.report_type,
            "sections":       self.sections,
            "cve_ids":        self.cve_ids,
            "technique_ids":  self.technique_ids,
            "hosts_affected": self.hosts_affected,
            "actions_taken":  self.actions_taken,
            "generated_at":   self.generated_at,
            "latency_s":      self.latency_s,
            "tokens_used":    self.tokens_used,
            "markdown":       self.markdown,
        }

    def _markdown_to_html(self) -> str:
        """Convert Markdown content to basic HTML (no external dependencies)."""
        severity_colour = _SEVERITY_COLOURS.get(self.severity, "#00aaff")
        body = self.markdown
        # Bold
        body = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", body)
        # Headers
        body = re.sub(r"^### (.+)$", r"<h3>\1</h3>", body, flags=re.MULTILINE)
        body = re.sub(r"^## (.+)$",  r"<h2>\1</h2>", body, flags=re.MULTILINE)
        body = re.sub(r"^# (.+)$",   r"<h1>\1</h1>", body, flags=re.MULTILINE)
        # List items
        body = re.sub(r"^- (.+)$", r"<li>\1</li>", body, flags=re.MULTILINE)
        # Newlines to paragraphs
        body = re.sub(r"\n\n", "</p><p>", body)
        body = f"<p>{body}</p>"

        return f"""<!DOCTYPE html>
<html><head>
<meta charset="utf-8">
<title>{self.title}</title>
<style>
  body {{ font-family: 'Segoe UI', sans-serif; max-width: 900px; margin: 40px auto;
          background: #040810; color: #e0eeff; padding: 20px; }}
  h1 {{ color: {severity_colour}; font-size: 1.8em; }}
  h2 {{ color: #00aaff; border-bottom: 1px solid #1a3a6a; padding-bottom: 6px; }}
  h3 {{ color: #ffaa00; }}
  .severity {{ background: {severity_colour}22; border: 1px solid {severity_colour};
               color: {severity_colour}; padding: 4px 12px; border-radius: 3px;
               display: inline-block; font-family: monospace; font-size: 0.85em; }}
  li {{ margin: 4px 0; }}
  p {{ line-height: 1.7; }}
</style>
</head><body>
<div class="severity">{self.severity}</div>
<h1>{self.title}</h1>
<p><small>Incident ID: {self.incident_id} | Generated: {self.generated_at}</small></p>
{body}
</body></html>"""

    def __str__(self) -> str:
        return (
            f"IncidentReport({self.incident_id!r}, "
            f"severity={self.severity!r}, "
            f"sections={list(self.sections.keys())})"
        )


class ReportGenerator:
    """
    Generates structured incident reports using the LLM pipeline.

    Parameters
    ----------
    llm : LLMClient
        LLM client for report generation.
    output_dir : str
        Directory to auto-save reports to.  Default ``"data/incidents"``.
    auto_save : bool
        If True, automatically save each report to ``output_dir``.
    """

    def __init__(
        self,
        llm:        LLMClient,
        output_dir: str  = "data/incidents",
        auto_save:  bool = False,
    ) -> None:
        self.llm        = llm
        self.output_dir = Path(output_dir)
        self.auto_save  = auto_save
        self._counter   = TokenCounter(model=llm.model)

        # Report history
        self._reports: List[IncidentReport] = []

    # ------------------------------------------------------------------ #
    # Primary interface
    # ------------------------------------------------------------------ #

    def generate(self, incident_context: Dict[str, Any]) -> IncidentReport:
        """
        Generate a full incident report from the incident context dict.

        Parameters
        ----------
        incident_context : dict
            Required keys: ``incident_id``, ``title``.
            Optional keys: all others listed in the class docstring.

        Returns
        -------
        IncidentReport
        """
        start = time.monotonic()

        incident_id    = incident_context.get("incident_id", self._next_id())
        title          = incident_context.get("title", "Unnamed Incident")
        severity       = incident_context.get("severity", "MEDIUM")
        report_type    = incident_context.get("report_type", "INCIDENT")

        logger.info("Generating incident report: %s — %s", incident_id, title)

        # Build the prompt
        prompt = PromptLibrary.incident_report(
            incident_id      = incident_id,
            title            = title,
            timeline         = incident_context.get("timeline", []),
            cve_ids          = incident_context.get("cve_ids", []),
            technique_ids    = incident_context.get("technique_ids", []),
            hosts_affected   = incident_context.get("hosts_affected", []),
            actions_taken    = incident_context.get("actions_taken", []),
            forgetting_delta = incident_context.get("forgetting_delta"),
            drift_detected   = incident_context.get("drift_detected", False),
        )

        messages = [
            {"role": "system", "content": PromptLibrary.system_incident_report()},
            {"role": "user",   "content": prompt},
        ]

        # Truncate if needed
        messages = self._counter.truncate_messages_to_budget(
            messages, reserved_for_completion=1500
        )

        resp = self.llm.chat(messages, max_tokens=1500, temperature=0.3)

        # Parse sections from the generated markdown
        sections = self._parse_report_sections(resp.content)

        # Build the report object
        report = IncidentReport(
            incident_id    = incident_id,
            title          = title,
            severity       = severity,
            report_type    = report_type,
            markdown       = self._build_full_markdown(
                incident_id, title, severity, resp.content, incident_context
            ),
            sections       = sections,
            cve_ids        = incident_context.get("cve_ids", []),
            technique_ids  = incident_context.get("technique_ids", []),
            hosts_affected = incident_context.get("hosts_affected", []),
            actions_taken  = incident_context.get("actions_taken", []),
            generated_at   = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            latency_s      = round(time.monotonic() - start, 3),
            tokens_used    = resp.total_tokens,
        )

        self._reports.append(report)

        if self.auto_save:
            report.save(str(self.output_dir / f"{incident_id}.md"))

        logger.info(
            "Report generated: %s — %.2fs, %d tokens",
            incident_id, report.latency_s, report.tokens_used,
        )
        return report

    def generate_drift_report(
        self,
        drift_event: Dict[str, Any],
        agent_metrics: Dict[str, Any],
    ) -> IncidentReport:
        """
        Generate a report specifically for a concept drift event.

        Parameters
        ----------
        drift_event : dict
            Drift event dict (from DriftInjector.drift_history).
        agent_metrics : dict
            Current agent metrics (from ACDPPOAgent.get_metrics()).

        Returns
        -------
        IncidentReport
        """
        incident_id = f"DRIFT-{drift_event.get('step', 0):07d}"
        context = {
            "incident_id":       incident_id,
            "title":             f"Concept Drift — {drift_event.get('description', '')}",
            "severity":          "HIGH",
            "report_type":       "DRIFT",
            "drift_detected":    True,
            "forgetting_delta":  agent_metrics.get("ewc_forgetting", 0.0),
            "timeline": [
                {
                    "timestamp": f"step {drift_event.get('step', 0)}",
                    "event":     "Wasserstein distance exceeded threshold",
                },
                {
                    "timestamp": f"step {drift_event.get('step', 0) + 1}",
                    "event":     "EWC task snapshot registered",
                },
                {
                    "timestamp": f"step {drift_event.get('step', 0) + 4000}",
                    "event":     "Incremental adaptation complete",
                },
            ],
            "cve_ids":        [],
            "technique_ids":  [],
            "hosts_affected": [],
            "actions_taken":  ["EWC Fisher update", "Incremental adaptation"],
        }
        return self.generate(context)

    def generate_session_summary(
        self,
        session_metrics: Dict[str, Any],
        incident_list:   List[IncidentReport],
    ) -> IncidentReport:
        """
        Generate an end-of-session summary report.

        Parameters
        ----------
        session_metrics : dict
            Agent training metrics for the session.
        incident_list : list[IncidentReport]
            All incidents that occurred during the session.

        Returns
        -------
        IncidentReport
        """
        all_cves       = list({c for r in incident_list for c in r.cve_ids})
        all_techniques = list({t for r in incident_list for t in r.technique_ids})
        all_hosts      = list({h for r in incident_list for h in r.hosts_affected})

        context = {
            "incident_id":    f"SUM-{time.strftime('%Y%m%d')}",
            "title":          "ACD Session Summary Report",
            "severity":       "MEDIUM",
            "report_type":    "SUMMARY",
            "cve_ids":        all_cves,
            "technique_ids":  all_techniques,
            "hosts_affected": all_hosts,
            "actions_taken":  [
                f"Total timesteps: {session_metrics.get('total_timesteps', 0):,}",
                f"Mean reward: {session_metrics.get('mean_reward', 0.0):.3f}",
                f"CVaR α=0.05: {session_metrics.get('cvar_005', 0.0):.3f}",
                f"Drift events: {session_metrics.get('drift_events', 0)}",
                f"EWC forgetting: {session_metrics.get('ewc_forgetting', 0.0):.4f}",
            ],
            "timeline": [
                {"timestamp": f"incident {i+1}", "event": r.title}
                for i, r in enumerate(incident_list)
            ],
        }
        return self.generate(context)

    # ------------------------------------------------------------------ #
    # History
    # ------------------------------------------------------------------ #

    @property
    def all_reports(self) -> List[IncidentReport]:
        """All generated reports in generation order."""
        return list(self._reports)

    def get_report(self, incident_id: str) -> Optional[IncidentReport]:
        """Return a report by incident ID."""
        return next(
            (r for r in self._reports if r.incident_id == incident_id),
            None,
        )

    # ------------------------------------------------------------------ #
    # Private helpers
    # ------------------------------------------------------------------ #

    @staticmethod
    def _parse_report_sections(text: str) -> Dict[str, str]:
        """
        Parse numbered report sections from LLM output.

        Handles formats like ``1. EXECUTIVE SUMMARY``, ``## Technical Details``.
        """
        section_map = {
            "EXECUTIVE SUMMARY":  "executive_summary",
            "TECHNICAL DETAILS":  "technical_details",
            "IMPACT":             "impact_assessment",
            "DEFENDER RESPONSE":  "defender_response",
            "TIMELINE":           "timeline",
            "RECOMMENDATIONS":    "recommendations",
        }

        result: Dict[str, str] = {v: "" for v in section_map.values()}

        header_pattern = re.compile(
            r"(?:\d+\.\s*|#+\s*)?"
            r"(" + "|".join(section_map.keys()) + r")"
            r"(?:\s*\n)",
            re.IGNORECASE,
        )

        parts = header_pattern.split(text)
        i = 1
        while i < len(parts) - 1:
            header  = parts[i].strip().upper()
            content = parts[i + 1].strip() if i + 1 < len(parts) else ""

            # Match header to section key
            for section_header, section_key in section_map.items():
                if section_header in header:
                    result[section_key] = content
                    break
            i += 2

        return result

    @staticmethod
    def _build_full_markdown(
        incident_id:      str,
        title:            str,
        severity:         str,
        llm_content:      str,
        context:          Dict[str, Any],
    ) -> str:
        """Wrap LLM-generated content with a structured Markdown header."""
        cve_line  = ", ".join(context.get("cve_ids", [])) or "None identified"
        tech_line = ", ".join(context.get("technique_ids", [])) or "None identified"
        host_line = ", ".join(context.get("hosts_affected", [])) or "None"

        header = (
            f"# {title}\n\n"
            f"**Incident ID:** {incident_id}  \n"
            f"**Severity:** {severity}  \n"
            f"**Generated:** {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}  \n"
            f"**CVEs:** {cve_line}  \n"
            f"**Techniques:** {tech_line}  \n"
            f"**Hosts:** {host_line}  \n\n"
            f"---\n\n"
        )
        return header + llm_content

    _report_counter = 0

    @classmethod
    def _next_id(cls) -> str:
        """Generate a sequential incident ID."""
        cls._report_counter += 1
        return f"INC-{time.strftime('%Y%m%d')}-{cls._report_counter:04d}"

    def __repr__(self) -> str:
        return (
            f"ReportGenerator("
            f"model={self.llm.model!r}, "
            f"n_reports={len(self._reports)})"
        )